### ISSUE TITLE
How to integrate it?

### ISSUE THREAD

**Issue by BirgerK** [bertramdev/seed-me#15]
Hi there,

I'm trying to use this plugin with Grails 3, so I added the line ``` compile 'com.bertramlabs.plugins:seed-me:3.0.6' ```to the dependencies. But it does not seed, even the command ``` run-seed ``` is not existing in grails-terminal.

What do I have to add build.gradle? Maybe others have the same problem, so some lines in project-readme would be helpfull. Or an example project.

Thank you!

**Comment by davydotcom** [comment]
You need to add to build script class path and apply plugin seed-me as well

**Comment by BirgerK** [comment]
My build.gradle contains
```
buildscript {
    ext {
        ...
    }
    repositories {
        ...
    }
    dependencies {
        ...
        classpath 'com.bertramlabs.plugins:seed-me:3.0.6'
    }
}
...
apply plugin: 'seed-me'

dependencies {
   ...
   compile 'com.bertramlabs.plugins:seed-me:3.0.6'
}
...
task copySeed(type: Copy){
    from "src/seed"
    into "seed"
}
processResources.dependsOn copySeed
```

I get no errors, but the command ``` grails run-seed ``` still cannot be found.
What to do?

**Comment by BirgerK** [comment]
Do you have a public github-project which uses seed-me?

**Comment by BirgerK** [comment]
anyone?

**Comment by bdwheeler** [comment]
Not seeing a public example on grails 3.  Converted some private - here's some info out of a private repo:
build.gradle

buildscript {
    dependencies {
        classpath "com.bertramlabs.plugins:seed-me:3.0.6"
    }
}
apply plugin:"seed-me"
dependencies {
  runtime "com.bertramlabs.plugins:seed-me:3.0.6"
}
BuildConfig.groovy
grails.project.dependency.resolution = {
  dependencies {
    compile ":seed-me:0.7.2"
  }
}
and application.groovy to enable 
environments {
    development {
        grails.plugin.seed.autoSeed = true
    }
}

**Comment by will-districtnerds** [comment]
@BirgerK, here you go. I forked the grails pet clinic project and ported data entry to use the seed-me plugin. https://github.com/will-districtnerds/grails-petclinic-seed-me-example
